// 自動生成（scripts/build.mjs）
export const API_LABEL = {
  "camera": "カメラ",
  "barcode": "バーコード検出",
  "notification": "通知",
  "storage": "端末内保存",
  "indexeddb": "IndexedDB",
  "geolocation": "位置情報",
  "orientation": "傾き・方位センサー",
  "motion": "加速度センサー",
  "share": "共有",
  "clipboard": "クリップボード",
  "vibration": "振動",
  "speech-recognition": "音声認識",
  "speech-synthesis": "音声読み上げ",
  "fetch": "外部API",
  "wake-lock": "画面スリープ防止",
  "microphone": "マイク",
  "web-audio": "Web Audio",
  "visibility": "ページ表示状態",
  "torch": "ライト",
  "media-recorder": "録音・録画",
  "canvas": "Canvas",
  "fullscreen": "全画面",
  "server": "サーバー必須",
  "webrtc": "WebRTC",
  "battery": "バッテリー",
  "service-worker": "オフライン",
  "file": "ファイル読み込み",
  "pointer": "タッチ・ペン",
  "keyboard": "キーボード",
  "webgpu": "WebGPU",
  "prompt-api": "ブラウザ内AI"
};
